model:
  base_model: "canopylabs/orpheus-tts-0.1-pretrained"
  target_sample_rate: 24000
  dtype: "bfloat16"
  device_map: "auto"
  trust_remote_code: true

# Training settings
training:
  epochs: 5
  batch_size: 2
  gradient_accumulation_steps: 32
  learning_rate: 0.00001
  warmup_steps: 100
  fp16: true
  logging_steps: 10
  save_steps: 400
  eval_steps: 200
  save_total_limit: 3
  remove_unused_columns: false
  dataloader_pin_memory: false
  
  # LoRA settings
  lora_r: 64
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"

  # Add gradient clipping
  max_grad_norm: 0.3

  # Wandb settings
  report_to: ["wandb"]
  wandb_project: "tts-finetune"
  wandb_run_name: "orpheus-tts-finetune"

# Data settings
data:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  max_audio_length: 30
  min_audio_length: 1
  seed: 42

# Generation settings
generation:
  temperature: 0.7
  top_p: 0.85
  repetition_penalty: 1.2
  max_tokens: 1024
  speed_factor: 0.9
  min_pause_duration: 0.15
  pause_token_weight: 1.1

# Audio settings
audio:
  channels: 1
  sample_width: 2
  sample_rate: 24000
  format: "wav"

# Output settings
output:
  model_dir: "finetuned_model"
  dataset_dir: "processed_dataset"
  audio_format: "wav"
  sample_rate: 24000

# SNAC model settings
snac:
  model_name: "hubertsiuzdak/snac_24khz" 